apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
        - name: student-management
          image: hsounasellami/student-management:1.0.0
          ports:
            - containerPort: 8089
          envFrom:
            - configMapRef:
                name: spring-config
            - secretRef:
                name: spring-secret
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: student-management
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
